FROM node:13.11.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
COPY webpack.config.dev.js /app/webpack.config.dev.js
COPY src /app/src
RUN npm install
RUN npm install react-scripts@3.3.1 -g --silent

CMD ["npm", "start"]